openapi: 3.0.1
info:
  title: Common Models
  version: 1.0.0
paths: {}
components:
  schemas:
    PageInfo:
      type: object
      properties:
        nextPage:
          type: string
          format: uri
          description: URL to the next page of results.
        prevPage:
          type: string
          format: uri
          description: URL to the previous page of results.
    Time:
      type: object
      example: "2024-02-06T15:45:30.123Z"
      description: |
        DateTime in ISO 8601 format: YYYY-MM-DDTHH:mm:ss.sssZ.
      properties:
        time:
          type: string
          format: date-time 
